# Versuch 2

In [3]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pandas as pd
from skimage.color import rgb2gray

## Aufgabe 1

### Zuerst Das Bild einlesen, croppen dessen Graustufen isolieren und deren Mittelwerte und Standardabweichungen berechnen.

In [7]:
img = cv2.imread("./versuch2-1_2.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

h, w = gray.shape
step = w // 5

cropped_imgs = []
for i in range(5):
    start = i * step
    end = (i + 1) * step
    cropped_imgs.append(gray[:, start:end])
print("Cropped imgs:", cropped_imgs)
means = [np.mean(i) for i in cropped_imgs]
stds = [np.std(i) for i in cropped_imgs]
print(f"Mittelwerte: {means}\nStandardabweichungen: {stds}")

print("Image Matrix:")
df = pd.DataFrame({
    "Stufe": range(1, 6),
    "Mittelwert": means,
    "Standardabweichung": stds
})

print(df)

Cropped imgs: [array([[205, 204, 205, ..., 212, 212, 211],
       [204, 205, 205, ..., 212, 212, 212],
       [207, 207, 206, ..., 212, 212, 212],
       ...,
       [212, 212, 212, ..., 200, 203, 204],
       [206, 206, 205, ..., 205, 204, 204],
       [210, 209, 210, ..., 206, 206, 206]], shape=(480, 128), dtype=uint8), array([[210, 210, 209, ..., 214, 214, 212],
       [211, 210, 210, ..., 213, 213, 213],
       [212, 212, 211, ..., 215, 214, 215],
       ...,
       [204, 201, 201, ..., 204, 204, 204],
       [205, 204, 203, ..., 204, 204, 204],
       [205, 204, 205, ..., 204, 204, 204]], shape=(480, 128), dtype=uint8), array([[212, 212, 212, ..., 217, 215, 215],
       [213, 212, 213, ..., 218, 215, 215],
       [216, 214, 214, ..., 217, 217, 216],
       ...,
       [204, 202, 203, ..., 204, 204, 204],
       [204, 203, 203, ..., 204, 204, 204],
       [204, 204, 204, ..., 204, 203, 203]], shape=(480, 128), dtype=uint8), array([[215, 217, 217, ..., 212, 212, 212],
       [215, 2

### Die isolierten Graustufen als Bilder dargestellt.

In [5]:
for i, c in enumerate(cropped_imgs):
    cv2.imshow(f"Stufe {i+1}", c)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Aufgabe 2

### Alle Schwarzbilder einlesen und sie in Graubilder übersetzen.

In [20]:
imgs = [cv2.imread(f"./versuch2-2_{i}.png") for i in range(1,10)]
gray = [cv2.cvtColor(i, cv2.COLOR_BGR2GRAY) for i in imgs]
gray = np.float64(gray)
print(gray)

[[[132. 131. 131. ... 126. 128. 128.]
  [132. 131. 131. ... 126. 128. 128.]
  [133. 132. 131. ... 126. 128. 128.]
  ...
  [127. 127. 127. ... 124. 123. 123.]
  [126. 126. 128. ... 121. 119. 119.]
  [125. 124. 124. ... 120. 122. 122.]]

 [[131. 128. 129. ... 124. 123. 123.]
  [128. 129. 130. ... 125. 125. 125.]
  [128. 127. 127. ... 127. 127. 127.]
  ...
  [125. 126. 125. ... 122. 122. 122.]
  [125. 126. 126. ... 118. 119. 119.]
  [123. 126. 124. ... 118. 119. 119.]]

 [[130. 127. 128. ... 125. 125. 125.]
  [130. 129. 127. ... 126. 127. 127.]
  [128. 130. 128. ... 127. 127. 127.]
  ...
  [123. 123. 124. ... 119. 118. 118.]
  [125. 125. 125. ... 117. 119. 119.]
  [125. 126. 127. ... 120. 121. 121.]]

 ...

 [[132. 131. 130. ... 124. 124. 124.]
  [130. 130. 130. ... 126. 127. 127.]
  [129. 129. 130. ... 127. 129. 129.]
  ...
  [127. 127. 126. ... 121. 122. 122.]
  [125. 125. 123. ... 120. 121. 121.]
  [125. 123. 124. ... 119. 121. 121.]]

 [[128. 128. 126. ... 126. 126. 126.]
  [128. 127.

### Alle pixelweisen Mittelwerte berechnen und und daraus ein "Bild von Mittelwerten" erstellen.

In [24]:
means = np.mean(imgs, axis=0)
means_max_contrast = cv2.normalize(means, None, 0, 255, cv2.NORM_MINMAX)
print(means_max_contrast)

cv2.imwrite("./versuch2-2_means_kontrastmaximiert.png", means_max_contrast)

[[[153.6023622  106.41732283 144.56692913]
  [122.48031496  98.38582677 138.54330709]
  [ 95.37401575  94.37007874 137.53937008]
  ...
  [ 56.22047244  74.29133858  98.38582677]
  [ 51.2007874   82.32283465 103.40551181]
  [ 49.19291339  82.32283465 105.41338583]]

 [[133.52362205 108.42519685 137.53937008]
  [114.4488189  102.4015748  141.55511811]
  [ 96.37795276 101.3976378  146.57480315]
  ...
  [ 64.2519685   80.31496063  86.33858268]
  [ 71.27952756  90.35433071  99.38976378]
  [ 71.27952756  90.35433071  99.38976378]]

 [[105.41338583 104.40944882 139.54724409]
  [ 92.36220472 106.41732283 146.57480315]
  [ 77.30314961 105.41338583 148.58267717]
  ...
  [ 84.33070866  85.33464567  99.38976378]
  [ 91.35826772  96.37795276 105.41338583]
  [ 91.35826772  96.37795276 105.41338583]]

 ...

 [[ 74.29133858  77.30314961 100.39370079]
  [ 70.27559055  74.29133858 110.43307087]
  [ 61.24015748  68.26771654 114.4488189 ]
  ...
  [ 53.20866142  39.15354331  51.2007874 ]
  [ 52.20472441  3

True

### Liest Dunkelbild ein, subtahiert von einem Eingabebild und gibt das korrigierte Bild aus.

In [41]:
# img: Eingabebild, src: Quellpfad des Dunkelbildes
def sub_from_img(src, img):
    d_src = cv2.imread(src)
    img = np.float64(img)
    mean = np.mean(img)
    means_mean = np.mean(mean)
    means_norm = means / means_mean # Mittelwert Kontrastmaximierung := 1
    print(means_norm)
    
    return img - d_src

## Aufgabe 3

### 10 Weißbilder einlesen, ihren Mittelwert berechnen, und davon das Dunkelbild berechnen.

In [43]:
imgs = [cv2.imread(f"./versuch2-3_{i}.png") for i in range(1,10)]

means_imgs = np.mean(imgs, axis=0)
#means_max_contrast = cv2.normalize(means, None, 0, 255, cv2.NORM_MINMAX)
#print(f"Mittelwert der 10 Weißbilder: {means_imgs}")
corr_img = sub_from_img("./dark.png", means_max_contrast)
print(f"Korrigiertes Bild: \n{corr_img}")
cv2.imwrite("./versuch2-3_kontrastmaximiert.png", corr_img)
div = corr_img / means_imgs
print(div)
cv2.imwrite("./versuch2-3_dividiert.png", div)


[[[1.0092862  0.9698544  1.00173543]
  [0.98327799 0.96314261 0.99670158]
  [0.96062568 0.95978671 0.99586261]
  ...
  [0.92790568 0.94300722 0.96314261]
  [0.92371081 0.94971902 0.96733748]
  [0.92203286 0.94971902 0.96901543]]

 [[0.99250671 0.97153235 0.99586261]
  [0.9765662  0.9664985  0.99921851]
  [0.96146466 0.96565953 1.00341338]
  ...
  [0.93461748 0.94804107 0.95307491]
  [0.9404903  0.95643081 0.96398158]
  [0.9404903  0.95643081 0.96398158]]

 [[0.96901543 0.96817645 0.99754056]
  [0.95810876 0.9698544  1.00341338]
  [0.94552414 0.96901543 1.00509133]
  ...
  [0.95139697 0.95223594 0.96398158]
  [0.95726979 0.96146466 0.96901543]
  [0.95726979 0.96146466 0.96901543]]

 ...

 [[0.94300722 0.94552414 0.96482056]
  [0.93965132 0.94300722 0.9732103 ]
  [0.93210055 0.93797338 0.9765662 ]
  ...
  [0.92538876 0.91364312 0.92371081]
  [0.92454978 0.91196517 0.92119389]
  [0.92706671 0.91196517 0.92119389]]

 [[0.94804107 0.9371344  0.96146466]
  [0.9438462  0.9404903  0.9698544 ]


True

## Aufgabe 4

In [50]:
dark = cv2.imread("dark.png", cv2.IMREAD_GRAYSCALE)
white = cv2.imread("versuch2-3_1.png", cv2.IMREAD_GRAYSCALE)

# Hot/Stuck Pixels: deutlich heller als der Rest
hot = dark > (np.mean(dark) + 5 * np.std(dark))

# Dead Pixels: deutlich dunkler als der Rest
dead = white < (np.mean(white) - 5 * np.std(white))

print("Hot pixels:", np.argwhere(hot))
print("Dead pixels:", np.argwhere(dead))


Hot pixels: [[  0 544]]
Dead pixels: []


### Durch obiges kann man sehen, dass es keine Dead Pixels auf dem Weißbild gibt und nur einen Hot Pixel auf dem Dunkelbild. Die markierte Stelle des Dunkelbildes ist unten vorzufinden.

<img src="./dark_stretched_markiert.png" />

In [57]:
img = cv2.imread("./versuch2-1_2.png")
corr = sub_from_img("./dark.png", img)
cv2.imwrite("./versuch4.png", corr)
print(corr)

[0.33022062 0.64892943 1.00077731 1.32177768 1.69829365]
[[[201. 204. 210.]
  [198. 202. 211.]
  [197. 202. 213.]
  ...
  [206. 207. 210.]
  [204. 206. 208.]
  [204. 206. 208.]]

 [[202. 202. 209.]
  [203. 202. 211.]
  [204. 201. 213.]
  ...
  [209. 207. 212.]
  [210. 208. 213.]
  [210. 208. 213.]]

 [[204. 205. 211.]
  [205. 204. 212.]
  [205. 203. 212.]
  ...
  [208. 209. 213.]
  [211. 210. 213.]
  [211. 210. 212.]]

 ...

 [[212. 212. 212.]
  [212. 212. 212.]
  [212. 212. 212.]
  ...
  [206. 198. 206.]
  [207. 198. 206.]
  [207. 198. 206.]]

 [[207. 203. 210.]
  [207. 204. 211.]
  [205. 203. 210.]
  ...
  [204. 197. 204.]
  [208. 197. 204.]
  [208. 197. 205.]]

 [[208. 206. 217.]
  [209. 206. 216.]
  [211. 206. 216.]
  ...
  [203. 198. 203.]
  [204. 196. 202.]
  [205. 196. 202.]]]


In [56]:
cropped_imgs = []
for i in range(5):
    start = i * step
    end = (i + 1) * step
    cropped_imgs.append(corr[:, start:end])
print("Cropped imgs:", cropped_imgs)
means = [np.mean(i) for i in cropped_imgs]
stds = [np.std(i) for i in cropped_imgs]
print(f"Mittelwerte: {means}\nStandardabweichungen: {stds}")

print("Image Matrix:")
df = pd.DataFrame({
    "Stufe": range(1, 6),
    "Mittelwert": means,
    "Standardabweichung": stds
})

print(df)

Cropped imgs: [array([[[201., 204., 210.],
        [198., 202., 211.],
        [197., 202., 213.],
        ...,
        [212., 211., 214.],
        [212., 211., 214.],
        [211., 210., 213.]],

       [[202., 202., 209.],
        [203., 202., 211.],
        [204., 201., 213.],
        ...,
        [212., 212., 213.],
        [212., 212., 212.],
        [212., 212., 213.]],

       [[204., 205., 211.],
        [205., 204., 212.],
        [205., 203., 212.],
        ...,
        [213., 211., 214.],
        [212., 211., 214.],
        [212., 211., 214.]],

       ...,

       [[212., 212., 212.],
        [212., 212., 212.],
        [212., 212., 212.],
        ...,
        [200., 200., 200.],
        [203., 203., 203.],
        [204., 204., 204.]],

       [[207., 203., 210.],
        [207., 204., 211.],
        [205., 203., 210.],
        ...,
        [209., 203., 206.],
        [210., 202., 207.],
        [210., 202., 207.]],

       [[208., 206., 217.],
        [209., 206., 216.],
 