# Versuch 2

In [5]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pandas as pd
from skimage.color import rgb2gray

## Aufgabe 1

### Zuerst Das Bild einlesen, croppen dessen Graustufen isolieren und deren Mittelwerte und Standardabweichungen berechnen.

In [10]:
img = cv2.imread("./versuch2-1_2.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

h, w = gray.shape
step = w // 5
# TODO: Fixe Fenster, damit nicht der Rand von der vorherigen Graustufe in der nächsten ist,.

cropped_imgs = [cv2.imread(f"./stufen_corrected/stufe_{i}.png") for i in range(1, 6)]
print("Cropped imgs:", cropped_imgs)
means = [np.mean(i) for i in cropped_imgs]
stds = [np.std(i) for i in cropped_imgs]
print(f"Mittelwerte: {means}\nStandardabweichungen: {stds}")

Cropped imgs: [array([[[31, 38, 37],
        [30, 36, 38],
        [30, 36, 40],
        ...,
        [35, 41, 48],
        [37, 42, 48],
        [35, 40, 44]],

       [[31, 37, 41],
        [29, 34, 39],
        [30, 33, 39],
        ...,
        [36, 41, 40],
        [37, 42, 39],
        [35, 43, 37]],

       [[31, 37, 41],
        [30, 33, 37],
        [33, 34, 39],
        ...,
        [37, 42, 39],
        [37, 42, 37],
        [35, 43, 37]],

       ...,

       [[39, 37, 37],
        [36, 35, 35],
        [36, 36, 36],
        ...,
        [32, 35, 35],
        [34, 36, 36],
        [35, 36, 36]],

       [[36, 36, 36],
        [36, 36, 36],
        [37, 37, 37],
        ...,
        [32, 35, 35],
        [36, 36, 36],
        [37, 36, 36]],

       [[31, 34, 40],
        [33, 35, 40],
        [35, 37, 39],
        ...,
        [33, 37, 38],
        [34, 36, 38],
        [35, 36, 37]]], shape=(452, 104, 3), dtype=uint8), array([[[ 78,  78,  78],
        [ 78,  78,  78],
     

### Die isolierten Graustufen als Bilder dargestellt.

In [11]:
for i, c in enumerate(cropped_imgs):
    cv2.imshow(f"Stufe {i+1}", c)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Aufgabe 2

### Alle Schwarzbilder einlesen und sie in Graubilder übersetzen.

In [12]:
imgs = [cv2.imread(f"./versuch2-2_{i}.png") for i in range(1,11)]
gray = [cv2.cvtColor(i, cv2.COLOR_BGR2GRAY) for i in imgs]
gray = np.float64(gray)
print(gray)

[[[132. 131. 131. ... 126. 128. 128.]
  [132. 131. 131. ... 126. 128. 128.]
  [133. 132. 131. ... 126. 128. 128.]
  ...
  [127. 127. 127. ... 124. 123. 123.]
  [126. 126. 128. ... 121. 119. 119.]
  [125. 124. 124. ... 120. 122. 122.]]

 [[131. 128. 129. ... 124. 123. 123.]
  [128. 129. 130. ... 125. 125. 125.]
  [128. 127. 127. ... 127. 127. 127.]
  ...
  [125. 126. 125. ... 122. 122. 122.]
  [125. 126. 126. ... 118. 119. 119.]
  [123. 126. 124. ... 118. 119. 119.]]

 [[130. 127. 128. ... 125. 125. 125.]
  [130. 129. 127. ... 126. 127. 127.]
  [128. 130. 128. ... 127. 127. 127.]
  ...
  [123. 123. 124. ... 119. 118. 118.]
  [125. 125. 125. ... 117. 119. 119.]
  [125. 126. 127. ... 120. 121. 121.]]

 ...

 [[128. 128. 126. ... 126. 126. 126.]
  [128. 127. 127. ... 123. 126. 126.]
  [129. 130. 130. ... 125. 127. 127.]
  ...
  [126. 126. 124. ... 121. 120. 120.]
  [127. 126. 124. ... 120. 120. 120.]
  [126. 127. 125. ... 119. 124. 124.]]

 [[130. 129. 128. ... 127. 127. 127.]
  [129. 128.

### Alle pixelweisen Mittelwerte berechnen und und daraus ein "Bild von Mittelwerten" erstellen.

In [14]:
means_mean = np.mean(means)
means_max_contrast = cv2.normalize(means_mean, None, 0, 255, cv2.NORM_MINMAX)

cv2.imwrite("./versuch2-2_means_kontrastmaximiert.png", means_max_contrast)

True

### Liest Dunkelbild ein, subtahiert von einem Eingabebild und gibt das korrigierte Bild aus.

In [15]:
# img: Eingabebild, src: Quellpfad des Dunkelbildes
def sub_from_img(src, img):
    d_src = cv2.imread(src)
    img = np.float64(img)
    mean = np.mean(img)
    means_mean = np.mean(mean)
    means_norm = means / means_mean # Mittelwert Kontrastmaximierung := 1
    print(means_norm)
    
    return img - d_src

## Aufgabe 3

### 10 Weißbilder einlesen, ihren Mittelwert berechnen, und davon das Dunkelbild berechnen.

In [17]:
imgs = [cv2.imread(f"./versuch2-3_{i}.png") for i in range(1,11)]

means_imgs = np.mean(imgs, axis=0)
means_max_contrast = cv2.normalize(means_imgs, None, 0, 255, cv2.NORM_MINMAX)
print(f"Mittelwert der 10 Weißbilder: {means_imgs}")
corr_img = sub_from_img("./dark.png", means_max_contrast)
print(f"Korrigiertes Bild: \n{corr_img}")
cv2.imwrite("./versuch2-3_kontrastmaximiert.png", corr_img)
div = corr_img / means_imgs
print(div)
cv2.imwrite("./versuch2-3_dividiert.png", div)


Mittelwert der 10 Weißbilder: [[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]
[inf inf inf inf inf]
Korrigiertes Bild: 
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0.

C:\Users\engel\AppData\Local\Temp\ipykernel_37212\1954944021.py:7: RuntimeWarning: divide by zero encountered in divide
  means_norm = means / means_mean # Mittelwert Kontrastmaximierung := 1


True

### Darstellung des kontrastmaximierten Bildes.
<img src="./versuch2-3_kontrastmaximiert.png" />

## Aufgabe 4

In [18]:
dark = cv2.imread("dark.png", cv2.IMREAD_GRAYSCALE)
white = cv2.imread("versuch2-3_1.png", cv2.IMREAD_GRAYSCALE)

# Hot/Stuck Pixels: deutlich heller als der Rest
hot = dark > (np.mean(dark) + 5 * np.std(dark))

# Dead Pixels: deutlich dunkler als der Rest
dead = white < (np.mean(white) - 5 * np.std(white))

print("Hot pixels:", np.argwhere(hot))
print("Dead pixels:", np.argwhere(dead))


Hot pixels: [[  0 544]]
Dead pixels: []


### Durch obiges kann man sehen, dass es keine Dead Pixels auf dem Weißbild gibt und nur einen Hot Pixel auf dem Dunkelbild. Die markierte Stelle des Dunkelbildes ist unten vorzufinden.

<img src="./dark_stretched_markiert.png" />

In [20]:
img = cv2.imread("./versuch2-1_2.png")
corr = sub_from_img("./dark.png", img)
cv2.imwrite("./versuch4.png", corr)
print(corr)

[0.26658914 0.61152702 0.97771142 1.32939537 1.73860184]
[[[201. 204. 210.]
  [198. 202. 211.]
  [197. 202. 213.]
  ...
  [206. 207. 210.]
  [204. 206. 208.]
  [204. 206. 208.]]

 [[202. 202. 209.]
  [203. 202. 211.]
  [204. 201. 213.]
  ...
  [209. 207. 212.]
  [210. 208. 213.]
  [210. 208. 213.]]

 [[204. 205. 211.]
  [205. 204. 212.]
  [205. 203. 212.]
  ...
  [208. 209. 213.]
  [211. 210. 213.]
  [211. 210. 212.]]

 ...

 [[212. 212. 212.]
  [212. 212. 212.]
  [212. 212. 212.]
  ...
  [206. 198. 206.]
  [207. 198. 206.]
  [207. 198. 206.]]

 [[207. 203. 210.]
  [207. 204. 211.]
  [205. 203. 210.]
  ...
  [204. 197. 204.]
  [208. 197. 204.]
  [208. 197. 205.]]

 [[208. 206. 217.]
  [209. 206. 216.]
  [211. 206. 216.]
  ...
  [203. 198. 203.]
  [204. 196. 202.]
  [205. 196. 202.]]]


### Korrigiertes Bild des Grauwertkeils.

<img src="./versuch4.png">

In [28]:
cropped_imgs = [cv2.imread(f"./stufen_corrected/stufe_{i}.png") for i in range(1, 6)]

means = [np.mean(i) for i in cropped_imgs]
stds = [np.std(i) for i in cropped_imgs]
print(f"Mittelwerte: {means}\nStandardabweichungen: {stds}")

print("Image Matrix:")
df = pd.DataFrame({
    "Stufe": range(1, 6),
    "Mittelwert": means,
    "Standardabweichung": stds
})

print(df)

Mittelwerte: [np.float64(32.158802756977536), np.float64(73.76886027572321), np.float64(117.94189664502164), np.float64(160.36573607534305), np.float64(209.72855067648993)]
Standardabweichungen: [np.float64(4.287599973346142), np.float64(3.94088242276356), np.float64(3.56076391729969), np.float64(3.469677794963058), np.float64(4.09150053337636)]
Image Matrix:
   Stufe  Mittelwert  Standardabweichung
0      1   32.158803            4.287600
1      2   73.768860            3.940882
2      3  117.941897            3.560764
3      4  160.365736            3.469678
4      5  209.728551            4.091501
